title: PhD Literature Review
date: 01/02/13

Gravity currents 
    Expressions for Froude number
        single layer
        linear
        two layer
    Life cycle
        single layer
        linear
        two layer

Similarity
    Justify the two layer system
        saharan air layer
        other atmospheric
        simple model (choi)
    Similarity between lab and field
        reynolds criterion
        turbulence in g.c.

Internal waves
    Linear theory
    Taylor goldstein
    modes
    Convective initiation
    nonlinear waves
        KdV
        BDO
        amplitude limits
    bores

Turbulence in g.c.
    Basic reynolds theory
    Research to date on turbulence in g.c.

Statistical methods
    Multivariate stats
    Autocorrelation
    Ensembles (estimation theory)
    DMD
        basics
        connection to other methods (a la Schmidt)
    Wavelets


Gravity currents
----------------

Releasing one fluid from behind a barrier into another fluid is a
conceptually simple problem that has generated a vast literature. We
refer to the movement of fluid following the release of the barrier
as a *gravity current*.

The simplicity of this problem leads to its appearance in a wide
variety of natural phenomena. The flow of water from the Amazon into
the Atlantic, fire propagation in buildings and carbon sequestration
are all examples in which gravity currents play a key role.

This work is primarily motivated by the occurence of gravity
currents in the atmosphere, in particular those generated in the
heart of the intense storm systems found in West Africa.

The behaviour of gravity currents is multifaceted and complex. The
turbulence in the core of a gravity current is sheared and
stratified, presenting a formidable problem.

When incident on a fluid of variable density fluid, gravity currents
display a wide range of interaction with waves in the fluid leading
to a zoo of phenomena.

### Fundamentals ###

Here we review the basic properties of gravity currents in a lab
setting.

The paradigm for the investigation of gravity currents in the
laboratory is the lock release experiment. A rectangular tank
(typically of dimensions $0.2m$ wide, $0.2m$ deep and between $1$ and
$6m$ long) has an impermeable barrier inserted transversely near to
one end, forming two distinct chambers in the tank. Each chamber is
filled with fluid of a different density, typically achieved using
varying concentrations of saline.

The experiment is initiated by quickly removing the gate. The fluids
are now in an unstable configuration and the resulting motion
creates a gravity current.

Other configurations are used to investigate gravity currents. We
might inject the dense fluid into the tank through a pipe, altering
the governing equations. 

Through the use of a conveyor belt in the floor of the tank and a
system for recirculating the ambient fluid through the tank (often
called a 'racetrack'), we can shift our frame of reference and
arrest the motion of the gravity current.  This allows for
investigation of the gravity current in the 'steady state' and the
choice of a slip or free-slip boundary condition at the base.





Similarity
----------




